/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import logic.Order;
import logic.PackingList;

/**
 *
 * @author Антон
 */
public class frmDirectorStorage extends javax.swing.JFrame {
    
    ArrayList<Order> orders;
    
    String OrderState1 = "На рассмотрении";
    String OrderState2 = "Принята";
    String OrderState3 = "Доставка";
    String PackingListState1 = "Открыта";
    String PackingListState2 = "В очереди";
    String PackingListState3 = "Закрыта";
    
    public frmDirectorStorage() {
        super("Работа начальника склада"); //Заголовок окна
        initComponents();
        addTabelOrder1();
        addTabelOrder2();
        addTabelPackingLists();
    }
    
    public void addTabelOrder1(){
        orders = new ArrayList<>();
        String[][] data = null;
        String[] columnNames = {"Статус","Сумма", "Размер", "Дата", "Район" ,"Имя заказчика", "Адрес заказчика", "Телефон заказчика", "id Заказчика"};
        Order order = new Order();
        orders = order.getByState(OrderState1);
        data = new String[orders.size()+1][9];
        if (orders.size()!= 0){
            for(int i=0; i < orders.size();i++){
                data[i][0]=orders.get(i).getState();
                data[i][1]=""+orders.get(i).getAmount();
                data[i][2]=""+orders.get(i).getSize();
                data[i][3]=""+orders.get(i).getDate();
                data[i][4]=""+orders.get(i).getDistrict().getDistrict();
                data[i][5]=""+orders.get(i).getCustomer().getName();
                data[i][6]=""+orders.get(i).getCustomer().getAddress();
                data[i][7]=""+orders.get(i).getCustomer().getPhone();
                data[i][8]=""+orders.get(i).getCustomer().getId();
            }
        }
        TableModel model = new DefaultTableModel(data, columnNames);
        tblOrder1.setModel(model);
    }
    
    public void addTabelOrder2(){
        orders = new ArrayList<>();
        String[][] data = null;
        String[] columnNames = {"Статус","Сумма", "Размер", "Дата", "Район" ,"Имя заказчика", "Адрес заказчика", "Телефон заказчика", "id Заказчика"};
        Order order = new Order();
        orders = order.getByState(OrderState2);
        data = new String[orders.size()+1][9];
        if (orders.size()!= 0){
            for(int i=0; i < orders.size();i++){
                data[i][0]=orders.get(i).getState();
                data[i][1]=""+orders.get(i).getAmount();
                data[i][2]=""+orders.get(i).getSize();
                data[i][3]=""+orders.get(i).getDate();
                data[i][4]=""+orders.get(i).getDistrict().getDistrict();
                data[i][5]=""+orders.get(i).getCustomer().getName();
                data[i][6]=""+orders.get(i).getCustomer().getAddress();
                data[i][7]=""+orders.get(i).getCustomer().getPhone();
                data[i][8]=""+orders.get(i).getCustomer().getId();
            }
        }
        TableModel model = new DefaultTableModel(data, columnNames);
        tblOrder2.setModel(model);
    }
    
    public void addTabelPackingLists(){
        ArrayList<PackingList> packingLists = new ArrayList<>();
        String[][] data = null;
        String[] columnNames = {"id","Статус","Район", "Размер", "Дата", "Авто"};
        PackingList packingList = new PackingList();
        packingLists = packingList.getByState(PackingListState1);
        data = new String[packingLists.size()+1][6];
        if (packingLists.size()!= 0){
            for(int i=0; i < packingLists.size();i++){
                data[i][0]=""+packingLists.get(i).getId();
                data[i][1]=packingLists.get(i).getState();
                data[i][2]=packingLists.get(i).getDistrict().getDistrict();
                data[i][3]=""+packingLists.get(i).getSize();
                data[i][4]=""+packingLists.get(i).getFirsDate();
                if(packingLists.get(i).getCar() == null){
                    data[i][5]="";
                }else{
                    data[i][5]=""+packingLists.get(i).getCar().getName();
                }
            }
        }
        TableModel model = new DefaultTableModel(data, columnNames);
        tblPackingLst.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnApprove = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrder2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPackingLst = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblOrder1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrder1);

        jLabel1.setText("Заявки на рассмотрении:");

        jButton2.setText("Закрыть");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnApprove.setText("Одобрить");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        tblOrder2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblOrder2);

        jLabel2.setText("Принятые заявки:");

        tblPackingLst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblPackingLst);

        jLabel3.setText("Открытые товарные накладные:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        jLabel4.setText("Товарные накладные в очереди:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1073, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnApprove))
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApprove)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        int id_order = 0;
        if (tblOrder1.getSelectedRow()>=0){
            Order order = new Order();
            System.err.println(tblOrder1.getValueAt(tblOrder1.getSelectedRow(), 8));
            if(tblOrder1.getValueAt(tblOrder1.getSelectedRow(), 8)!=null){
                id_order = Integer.parseInt((tblOrder1.getValueAt(tblOrder1.getSelectedRow(), 8)).toString());
                order = order.getById(id_order);
                if (order!=null){
                     order.OrderInAccepted();
                      addTabelOrder1();
                      addTabelOrder2();
                      addTabelPackingLists();
                }
            }
            
        }
        
    }//GEN-LAST:event_btnApproveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDirectorStorage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDirectorStorage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDirectorStorage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDirectorStorage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDirectorStorage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblOrder1;
    private javax.swing.JTable tblOrder2;
    private javax.swing.JTable tblPackingLst;
    // End of variables declaration//GEN-END:variables
}
